# Generated by Skyramp v1.3.16 on 2026-04-13 04:27:00.310369083 +0000 UTC m=+346.142603669
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output add_body_params_custom_accepted_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_add-body-params-custom-accepted.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    articles_POST_request_body = r'''{
        "clientMutationId": "mutation-abc-123",
        "data": {
            "slug": "custom-param-article-accepted",
            "title": "Custom Param Article"
        }
    }'''
    
    # Execute Request
    articles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_POST_response.status_code == 201
    assert skyramp.get_response_value(articles_POST_response, "data") is not None
    assert skyramp.get_response_value(articles_POST_response, "data.documentId") is not None
    assert skyramp.get_response_value(articles_POST_response, "data.title") == "Custom Param Article"
    assert skyramp.get_response_value(articles_POST_response, "data.slug") == "custom-param-article-accepted"


if __name__ == "__main__":
    test_integration()
