# Generated by Skyramp v1.3.16 on 2026-04-13 04:25:34.808417778 +0000 UTC m=+256.762309877
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output addinputparams_validation_reject_invalid_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_addinputparams-validation-reject-invalid.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    test2_POST_request_body = r'''{
        "data": {
            "name": "valid-addinput-test-resource"
        }
    }'''
    
    # Execute Request
    test2_POST_response = client.send_request(
        url=URL_localhost,
        path="/test2",
        method="POST",
        body=test2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert test2_POST_response.status_code == 201
    assert skyramp.get_response_value(test2_POST_response, "data.id") is not None
    assert skyramp.get_response_value(test2_POST_response, "data.name") == "valid-addinput-test-resource"

    # Request Body
    test2_POST_1_request_body = r'''{
        "data": {
            "id": 99,
            "name": "reserved-key-test-resource"
        }
    }'''
    
    # Execute Request
    test2_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/test2",
        method="POST",
        body=test2_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert test2_POST_1_response.status_code == 400
    assert skyramp.get_response_value(test2_POST_1_response, "error.status") == 400


if __name__ == "__main__":
    test_integration()
