# Generated by Skyramp v1.3.16 on 2026-04-13 04:25:32.53836458 +0000 UTC m=+254.492256679
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output addinputparams_rename_backward_compat_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_addinputparams-rename-backward-compat.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    foo_PUT_request_body = r'''{
        "data": {
            "title": "backward-compat-test"
        }
    }'''
    
    # Execute Request
    foo_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/foo",
        method="PUT",
        body=foo_PUT_request_body,
        headers=headers
    )
    # Generated Assertions
    assert foo_PUT_response.status_code == 200
    assert skyramp.get_response_value(foo_PUT_response, "data.id") is not None
    assert skyramp.get_response_value(foo_PUT_response, "data.title") == "backward-compat-test"

    # Request Body
    foo_PUT_1_request_body = r'''{
        "data": {
            "clientMutationId": "compat-mut-001",
            "title": "backward-compat-test"
        }
    }'''
    
    # Execute Request
    foo_PUT_1_response = client.send_request(
        url=URL_localhost,
        path="/api/foo",
        method="PUT",
        body=foo_PUT_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert foo_PUT_1_response.status_code == 200
    assert skyramp.get_response_value(foo_PUT_1_response, "data.id") is not None
    assert skyramp.get_response_value(foo_PUT_1_response, "data.title") == "backward-compat-test"


if __name__ == "__main__":
    test_integration()
