# Generated by Skyramp v1.3.16 on 2026-04-13 04:25:37.005855776 +0000 UTC m=+258.959747895
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output addqueryparams_strict_param_rejection_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_addqueryparams-strict-param-rejection.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    test1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/test1",
        method="GET",
        headers=headers,
        query_params={"fields": ["name"]}
    )
    # Generated Assertions
    assert test1_GET_response.status_code == 200
    assert skyramp.get_response_value(test1_GET_response, "data") is not None

    # Execute Request
    test1_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/test1",
        method="GET",
        headers=headers,
        query_params={"strictlyRejectedUnknownParam": ["value"]}
    )
    # Generated Assertions
    assert test1_GET_1_response.status_code == 400
    assert skyramp.get_response_value(test1_GET_1_response, "error.status") == 400


if __name__ == "__main__":
    test_integration()
