# Generated by Skyramp v1.3.16 on 2026-04-12 23:47:56.298024694 +0000 UTC m=+121.585832070
# Command: skyramp generate contract rest http://localhost:1337/bar \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--request-data {"data":{"name":"test-bar-update","value":"updated-value"}} \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

# contract test for /bar PATCH
def test_bar_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bar_PATCH_request_body = r'''{
        "data": {
            "name": "test-bar-update",
            "value": "updated-value"
        }
    }'''

    # Execute Request
    bar_PATCH_response = client.send_request(
        url=URL,
        path="/bar",
        method="PATCH",
        body=bar_PATCH_request_body,
        headers=headers
    )

    # Generated Assertions
    assert bar_PATCH_response.status_code == 401


if __name__ == "__main__":
    test_bar_patch()
