# Generated by Skyramp v1.3.19 on 2026-04-15 07:10:12.554020264 +0000 UTC m=+126.387487369
# Command: skyramp generate contract rest http://localhost/bar \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output bar_patch_401_contract_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost")

# contract test for /bar PATCH
def test_bar_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    bar_PATCH_response = client.send_request(
        url=URL,
        path="/bar",
        method="PATCH",
        headers=headers
    )

    # Generated Assertions
    assert bar_PATCH_response.status_code == 401


if __name__ == "__main__":
    test_bar_patch()
