// Generated by Skyramp v1.3.16 on 2026-04-13 02:22:21.440564605 +0000 UTC m=+389.660896206
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output bidirectional_relation_order_preservation_integration_test.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_bidirectional-relation-order-preservation.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const apiPostRequestBody = `{
            "name": "OrderTagA-skyramp"
        }`

    // Execute Request
    let apiPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/content-manager/collection-types/api::tag.tag",
        method:"POST",
        body:apiPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(apiPostResponse.statusCode, 'status code').toBe(201);
    expect(getValue(apiPostResponse, "documentId"), 'documentId').not.toBeNull();
    expect(getValue(apiPostResponse, "name"), 'name').toBe("OrderTagA-skyramp");
    let api_tag_tag = getValue(apiPostResponse, "documentId");

    // Request Body
    const apiPost1RequestBody = `{
            "name": "OrderProduct-skyramp",
            "tags": {
                "connect": [
                    {
                        "documentId": "${api_tag_tag}"
                    }
                ]
            }
        }`

    // Execute Request
    let apiPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/content-manager/collection-types/api::product.product",
        method:"POST",
        body:apiPost1RequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(apiPost1Response.statusCode, 'status code').toBe(201);
    expect(getValue(apiPost1Response, "documentId"), 'documentId').not.toBeNull();
    expect(getValue(apiPost1Response, "name"), 'name').toBe("OrderProduct-skyramp");
    let api_product_product = getValue(apiPost1Response, "documentId");

    // Request Body
    const publishPostRequestBody = `{}`

    // Execute Request
    let publishPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/content-manager/collection-types/api::product.product/{api::product.product}/actions/publish",
        method:"POST",
        body:publishPostRequestBody,
        headers:headers,
        pathParams:{"api::product.product": api_product_product}
    });

    // Generated Assertions
    expect(publishPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(publishPostResponse, "documentId"), 'documentId').not.toBeNull();
    expect(getValue(publishPostResponse, "publishedAt"), 'publishedAt').not.toBeNull();

    // Execute Request
    let apiProductProductGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/content-manager/collection-types/api::product.product/{api::product.product}",
        method:"GET",
        headers:headers,
        pathParams:{"api::product.product": api_product_product},
        queryParams:{"populate": ["tags"]}
    });

    // Generated Assertions
    expect(apiProductProductGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(apiProductProductGetResponse, "documentId"), 'documentId').not.toBeNull();
    expect(getValue(apiProductProductGetResponse, "name"), 'name').toBe("OrderProduct-skyramp");
    expect(getValue(apiProductProductGetResponse, "tags.0.documentId"), 'tags.0.documentId').not.toBeNull();
});

