# Generated by Skyramp v1.3.16 on 2026-04-13 02:14:19.585640604 +0000 UTC m=+266.865847494
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output connect_disconnect_relations_fk_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_connect-disconnect-relations-fk.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    authors_POST_request_body = r'''{
        "data": {
            "name": "FK Connect Test Author"
        }
    }'''

    # Execute Request
    authors_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_response.status_code == 201
    assert skyramp.get_response_value(authors_POST_response, "data.id") is not None
    assert skyramp.get_response_value(authors_POST_response, "data.attributes.name") == "FK Connect Test Author"

    # Request Body
    articles_POST_request_body = r'''{
        "data": {
            "title": "FK Connect Test Article"
        }
    }'''

    # Execute Request
    articles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_POST_response.status_code == 201
    assert skyramp.get_response_value(articles_POST_response, "data.id") is not None
    assert skyramp.get_response_value(articles_POST_response, "data.attributes.title") == "FK Connect Test Article"

    # Request Body
    articles_articles_PUT_request_body = '{"data": {"authors": {"connect": [{"id": ' + str(skyramp.get_response_value(authors_POST_response, "data.id")) + '}]}}}'

    # Execute Request
    articles_articles_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/articles/{articles}",
        method="PUT",
        body=articles_articles_PUT_request_body,
        headers=headers,
        path_params={"articles": skyramp.get_response_value(articles_POST_response, "data.id")}
    )
    # Generated Assertions
    assert articles_articles_PUT_response.status_code == 200
    assert skyramp.get_response_value(articles_articles_PUT_response, "data.id") is not None

    # Execute Request
    articles_articles_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/articles/{articles}",
        method="GET",
        headers=headers,
        path_params={"articles": skyramp.get_response_value(articles_POST_response, "data.id")}
    )
    # Generated Assertions
    assert articles_articles_GET_response.status_code == 200
    assert skyramp.get_response_value(articles_articles_GET_response, "data.id") == skyramp.get_response_value(articles_POST_response, "data.id")
    assert skyramp.get_response_value(articles_articles_GET_response, "data.attributes.title") == "FK Connect Test Article"

    # Request Body
    articles_articles_PUT_1_request_body = '{"data": {"authors": {"disconnect": [{"id": ' + str(skyramp.get_response_value(authors_POST_response, "data.id")) + '}]}}}'

    # Execute Request
    articles_articles_PUT_1_response = client.send_request(
        url=URL_localhost,
        path="/api/articles/{articles}",
        method="PUT",
        body=articles_articles_PUT_1_request_body,
        headers=headers,
        path_params={"articles": skyramp.get_response_value(articles_POST_response, "data.id")}
    )
    # Generated Assertions
    assert articles_articles_PUT_1_response.status_code == 200
    assert skyramp.get_response_value(articles_articles_PUT_1_response, "data.id") is not None


if __name__ == "__main__":
    test_integration()
