// Generated by Skyramp v1.3.16 on 2026-04-13 00:58:03.953437378 +0000 UTC m=+82.173739435
// Command: skyramp generate contract rest http://localhost:1337/bar \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output contract_patch_bar.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
// 		--overwrite \
// 		--request-data {"name":"updated-bar"} \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, MockV2, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /bar PATCH
test('testBarPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const barPatchRequestBody: string = `{
        "name": "updated-bar"
    }`;

    // Configure mock response
    const mock = new MockV2({
        url: URL,
        path: "/bar",
        method: "PATCH",
        statusCode: 401,
        requestBody: barPatchRequestBody
    });
    await client.applyMock(mock);

    // Execute Request
    const barPatchResponse = await client.sendRequest({
        url: URL,
        path: "/bar",
        method: "PATCH",
        body: barPatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(barPatchResponse.statusCode, 'status code').toBe(401);

    await client.removeAllMocks();
});
