# Generated by Skyramp v1.3.16 on 2026-04-13 00:59:11.450879535 +0000 UTC m=+91.498725026
# Command: skyramp generate contract rest http://localhost:1337/bar \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PATCH \
# 		--output contract_patch_bar_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"test-bar-update"} \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

# contract test for /bar PATCH
def test_bar_patch():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    bar_PATCH_request_body = r'''{
        "name": "test-bar-update"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/bar",
        method="PATCH",
        status_code=401,
        request_body=bar_PATCH_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    bar_PATCH_response = client.send_request(
        url=URL,
        path="/bar",
        method="PATCH",
        body=bar_PATCH_request_body,
        headers=headers
    )

    # Generated Assertions
    assert bar_PATCH_response.status_code == 401

    client.remove_all_mocks()


if __name__ == "__main__":
    test_bar_patch()
