// Generated by Skyramp v1.3.16 on 2026-04-13 00:58:06.099053982 +0000 UTC m=+84.319356039
// Command: skyramp generate contract rest http://localhost:1337/api/foo \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output contract_put_api_foo.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
// 		--overwrite \
// 		--request-data {"data":{"name":"updated-foo"}} \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, MockV2, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /api/foo PUT
test('testApiFooPut', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const apiFooPutRequestBody: string = `{
        "data": {
            "name": "updated-foo"
        }
    }`;

    // Configure mock response
    const mock = new MockV2({
        url: URL,
        path: "/api/foo",
        method: "PUT",
        statusCode: 401,
        requestBody: apiFooPutRequestBody
    });
    await client.applyMock(mock);

    // Execute Request
    const apiFooPutResponse = await client.sendRequest({
        url: URL,
        path: "/api/foo",
        method: "PUT",
        body: apiFooPutRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(apiFooPutResponse.statusCode, 'status code').toBe(401);

    await client.removeAllMocks();
});
