# Generated by Skyramp v1.3.16 on 2026-04-13 00:59:14.997283377 +0000 UTC m=+87.281086491
# Command: skyramp generate contract rest http://localhost:1337/api/foo \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output contract_put_api_foo.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

# contract test for /api/foo PUT
def test_api_foo_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/foo",
        method="PUT",
        status_code=401
    )
    client.apply_mock(mock)

    # Execute Request
    api_foo_PUT_response = client.send_request(
        url=URL,
        path="/api/foo",
        method="PUT",
        headers=headers
    )

    # Generated Assertions
    assert api_foo_PUT_response.status_code == 401

    client.remove_all_mocks()


if __name__ == "__main__":
    test_api_foo_put()
