# Generated by Skyramp v1.3.16 on 2026-04-13 02:14:14.573757956 +0000 UTC m=+261.853964829
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output delete_entity_multiple_relations_fk_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_delete-entity-multiple-relations-fk.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    authors_POST_request_body = r'''{
        "data": {
            "name": "Author One FK Test"
        }
    }'''

    # Execute Request
    authors_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_response.status_code == 201
    assert skyramp.get_response_value(authors_POST_response, "data.id") is not None
    assert skyramp.get_response_value(authors_POST_response, "data.attributes.name") == "Author One FK Test"

    # Request Body
    authors_POST_1_request_body = r'''{
        "data": {
            "name": "Author Two FK Test"
        }
    }'''

    # Execute Request
    authors_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/authors",
        method="POST",
        body=authors_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert authors_POST_1_response.status_code == 201
    assert skyramp.get_response_value(authors_POST_1_response, "data.id") is not None
    assert skyramp.get_response_value(authors_POST_1_response, "data.attributes.name") == "Author Two FK Test"

    # Request Body
    articles_POST_request_body = '{"data": {"authors": {"connect": [{"id": ' + str(skyramp.get_response_value(authors_POST_response, "data.id")) + '}, {"id": ' + str(skyramp.get_response_value(authors_POST_1_response, "data.id")) + '}]}, "title": "FK Delete Test Article"}}'

    # Execute Request
    articles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_POST_response.status_code == 201
    assert skyramp.get_response_value(articles_POST_response, "data.id") is not None
    assert skyramp.get_response_value(articles_POST_response, "data.attributes.title") == "FK Delete Test Article"

    # Execute Request
    articles_articles_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/articles/{articles}",
        method="DELETE",
        headers=headers,
        path_params={"articles": skyramp.get_response_value(articles_POST_response, "data.id")}
    )
    # Generated Assertions
    assert articles_articles_DELETE_response.status_code == 204

    # Execute Request
    articles_articles_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/articles/{articles}",
        method="GET",
        headers=headers,
        path_params={"articles": skyramp.get_response_value(articles_POST_response, "data.id")}
    )
    # Generated Assertions
    assert articles_articles_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
