# Generated by Skyramp v1.3.16 on 2026-04-13 04:23:59.761335248 +0000 UTC m=+226.930669787
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output delete_api_test3_cascade_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_delete-api-test3-cascade.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    test3_POST_request_body = r'''{
        "data": {
            "name": "test3-cascade-entry",
            "status": "active"
        }
    }'''

    # Execute Request
    test3_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/test3",
        method="POST",
        body=test3_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert test3_POST_response.status_code == 201
    assert skyramp.get_response_value(test3_POST_response, "data.id") is not None
    assert skyramp.get_response_value(test3_POST_response, "data.attributes.name") == "test3-cascade-entry"
    assert skyramp.get_response_value(test3_POST_response, "data.attributes.status") == "active"

    # Execute Request
    test3_test3_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/test3/{test3}",
        method="DELETE",
        headers=headers,
        path_params={"test3": skyramp.get_response_value(test3_POST_response, "data.id")}
    )
    # Generated Assertions
    assert test3_test3_DELETE_response.status_code == 204

    # Execute Request
    test3_test3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/test3/{test3}",
        method="GET",
        headers=headers,
        path_params={"test3": skyramp.get_response_value(test3_POST_response, "data.id")}
    )
    # Generated Assertions
    assert test3_test3_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
