# Generated by Skyramp v1.3.16 on 2026-04-13 02:14:17.237993773 +0000 UTC m=+264.518200650
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output delete_entity_all_relations_fk_multi_type_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_delete-entity-all-relations-fk-multi-type.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    categories_POST_request_body = r'''{
        "data": {
            "shorttext": "Test Category FK Multi"
        }
    }'''

    # Execute Request
    categories_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/categories",
        method="POST",
        body=categories_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert categories_POST_response.status_code == 201
    assert skyramp.get_response_value(categories_POST_response, "data.id") is not None
    assert skyramp.get_response_value(categories_POST_response, "data.attributes.shorttext") == "Test Category FK Multi"

    # Request Body
    complexes_POST_request_body = '{"data": {"categories_m2m": {"connect": [{"id": ' + str(skyramp.get_response_value(categories_POST_response, "data.id")) + '}]}, "required": "fk-multi-type-test", "shorttext": "FK Multi Type Complex"}}'

    # Execute Request
    complexes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/complexes",
        method="POST",
        body=complexes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert complexes_POST_response.status_code == 201
    assert skyramp.get_response_value(complexes_POST_response, "data.id") is not None
    assert skyramp.get_response_value(complexes_POST_response, "data.attributes.required") == "fk-multi-type-test"
    assert skyramp.get_response_value(complexes_POST_response, "data.attributes.shorttext") == "FK Multi Type Complex"

    # Execute Request
    complexes_complexes_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/complexes/{complexes}",
        method="DELETE",
        headers=headers,
        path_params={"complexes": skyramp.get_response_value(complexes_POST_response, "data.id")}
    )
    # Generated Assertions
    assert complexes_complexes_DELETE_response.status_code == 204

    # Execute Request
    complexes_complexes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/complexes/{complexes}",
        method="GET",
        headers=headers,
        path_params={"complexes": skyramp.get_response_value(complexes_POST_response, "data.id")}
    )
    # Generated Assertions
    assert complexes_complexes_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
