# Generated by Skyramp v1.3.16 on 2026-04-13 04:31:10.788285165 +0000 UTC m=+639.323355660
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output fill_from_locale_localized_relation_happy_path_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_fill-from-locale-localized-relation-happy-path.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    locale = "en"
    targetLocale = "fr"

    # Execute Request
    locales_GET_response = client.send_request(
        url=URL_localhost,
        path="/i18n/locales",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert locales_GET_response.status_code == 200
    assert skyramp.get_response_value(locales_GET_response, "0") is not None

    # Request Body
    api_POST_request_body = r'''{
        "name": "TestCountryFFLEN"
    }'''

    # Execute Request
    api_POST_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::country.country",
        method="POST",
        body=api_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert api_POST_response.status_code == 200
    assert skyramp.get_response_value(api_POST_response, "documentId") is not None
    assert skyramp.get_response_value(api_POST_response, "name") == "TestCountryFFLEN"

    # Request Body
    api_country_country_PUT_request_body = r'''{
        "name": "TestCountryFFLFR"
    }'''

    # Execute Request
    api_country_country_PUT_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::country.country/" + str(skyramp.get_response_value(api_POST_response, "documentId")),
        method="PUT",
        body=api_country_country_PUT_request_body,
        headers=headers,
        query_params={"locale": targetLocale}
    )
    # Generated Assertions
    assert api_country_country_PUT_response.status_code == 200
    assert skyramp.get_response_value(api_country_country_PUT_response, "documentId") is not None
    assert skyramp.get_response_value(api_country_country_PUT_response, "name") == "TestCountryFFLFR"

    # Request Body - chaining documentId from country POST response
    api_POST_1_request_body = '{"countries":{"connect":[{"documentId":"' + str(skyramp.get_response_value(api_POST_response, "documentId")) + '"}]},"isAvailable":true,"name":"TestProductFFLHappyPath"}'

    # Execute Request
    api_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::product.product",
        method="POST",
        body=api_POST_1_request_body,
        headers=headers,
        query_params={"locale": locale}
    )
    # Generated Assertions
    assert api_POST_1_response.status_code == 200
    assert skyramp.get_response_value(api_POST_1_response, "documentId") is not None
    assert skyramp.get_response_value(api_POST_1_response, "name") == "TestProductFFLHappyPath"
    assert skyramp.get_response_value(api_POST_1_response, "isAvailable") == True

    # Execute Request
    get_fill_from_locale_api_GET_response = client.send_request(
        url=URL_localhost,
        path="/i18n/content-manager/get-fill-from-locale/api::product.product",
        method="GET",
        headers=headers,
        query_params={
            "collectionType": "collection-types",
            "documentId": skyramp.get_response_value(api_POST_1_response, "documentId"),
            "sourceLocale": locale,
            "targetLocale": targetLocale
        }
    )
    # Generated Assertions
    assert get_fill_from_locale_api_GET_response.status_code == 200
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data") is not None
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.name") == "TestProductFFLHappyPath"
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.countries.connect") is not None
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.countries.connect.0.locale") == "fr"


if __name__ == "__main__":
    test_integration()
