# Generated by Skyramp v1.3.16 on 2026-04-13 04:31:13.53656194 +0000 UTC m=+642.071632435
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output fill_from_locale_component_nested_relations_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_fill-from-locale-component-nested-relations.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    locale = "en"
    targetLocale = "fr"

    # Execute Request - Get existing authors to chain documentId
    api_GET_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::author.author",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert api_GET_response.status_code == 200
    assert skyramp.get_response_value(api_GET_response, "results") is not None

    # Request Body - chain author documentId from GET response
    api_POST_request_body = '{"title":"ComponentNestedArticleFFLTest","content":[],"seo":{"title":"SEO Title FFL Test","description":"SEO Description FFL Test","indexable":true},"authors":{"connect":[{"documentId":"' + str(skyramp.get_response_value(api_GET_response, "results.0.documentId")) + '"}]}}'

    # Execute Request - Create article with seo component and authors relation
    api_POST_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::article.article",
        method="POST",
        body=api_POST_request_body,
        headers=headers,
        query_params={"locale": locale}
    )
    # Generated Assertions
    assert api_POST_response.status_code == 200
    assert skyramp.get_response_value(api_POST_response, "documentId") is not None
    assert skyramp.get_response_value(api_POST_response, "title") == "ComponentNestedArticleFFLTest"

    # Execute Request - Verify fill from locale preserves component and relation data
    get_fill_from_locale_api_GET_response = client.send_request(
        url=URL_localhost,
        path="/i18n/content-manager/get-fill-from-locale/api::article.article",
        method="GET",
        headers=headers,
        query_params={
            "collectionType": "collection-types",
            "documentId": skyramp.get_response_value(api_POST_response, "documentId"),
            "sourceLocale": locale,
            "targetLocale": targetLocale
        }
    )
    # Generated Assertions
    assert get_fill_from_locale_api_GET_response.status_code == 200
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data") is not None
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.title") == "ComponentNestedArticleFFLTest"
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.seo") is not None
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.authors.connect") is not None


if __name__ == "__main__":
    test_integration()
