# Generated by Skyramp v1.3.16 on 2026-04-13 04:31:15.663684456 +0000 UTC m=+644.198754951
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output fill_from_locale_dynamic_zone_relations_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_fill-from-locale-dynamic-zone-relations.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    sourceLocale = "en"
    targetLocale = "fr"

    # Request Body
    api_POST_request_body = r'''{
        "isAvailable": true,
        "name": "DZTestProductEN"
    }'''

    # Execute Request - Create EN product
    api_POST_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::product.product",
        method="POST",
        body=api_POST_request_body,
        headers=headers,
        query_params={"locale": sourceLocale}
    )
    # Generated Assertions
    assert api_POST_response.status_code == 200
    assert skyramp.get_response_value(api_POST_response, "documentId") is not None
    assert skyramp.get_response_value(api_POST_response, "name") == "DZTestProductEN"

    # Request Body
    api_product_product_PUT_request_body = r'''{
        "isAvailable": true,
        "name": "DZTestProductFR"
    }'''

    # Execute Request - Create FR locale translation of product
    api_product_product_PUT_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::product.product/" + str(skyramp.get_response_value(api_POST_response, "documentId")),
        method="PUT",
        body=api_product_product_PUT_request_body,
        headers=headers,
        query_params={"locale": targetLocale}
    )
    # Generated Assertions
    assert api_product_product_PUT_response.status_code == 200
    assert skyramp.get_response_value(api_product_product_PUT_response, "documentId") is not None

    # Request Body - chain product documentId into dynamic zone relation
    api_POST_1_request_body = '{"title":"DZTestShopEN","content":[{"__component":"page-blocks.product-carousel","title":"Featured Products","products":{"connect":[{"documentId":"' + str(skyramp.get_response_value(api_POST_response, "documentId")) + '"}]}}]}'

    # Execute Request - Create EN shop with product in dynamic zone
    api_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/content-manager/collection-types/api::shop.shop",
        method="POST",
        body=api_POST_1_request_body,
        headers=headers,
        query_params={"locale": sourceLocale}
    )
    # Generated Assertions
    assert api_POST_1_response.status_code == 200
    assert skyramp.get_response_value(api_POST_1_response, "documentId") is not None
    assert skyramp.get_response_value(api_POST_1_response, "title") == "DZTestShopEN"

    # Execute Request - Verify fill from locale resolves dynamic zone relations to target locale
    get_fill_from_locale_api_GET_response = client.send_request(
        url=URL_localhost,
        path="/i18n/content-manager/get-fill-from-locale/api::shop.shop",
        method="GET",
        headers=headers,
        query_params={
            "collectionType": "collection-types",
            "documentId": skyramp.get_response_value(api_POST_1_response, "documentId"),
            "sourceLocale": sourceLocale,
            "targetLocale": targetLocale
        }
    )
    # Generated Assertions
    assert get_fill_from_locale_api_GET_response.status_code == 200
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data") is not None
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.title") == "DZTestShopEN"
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.content") is not None
    assert skyramp.get_response_value(get_fill_from_locale_api_GET_response, "data.content.0.products.connect.0.locale") == "fr"


if __name__ == "__main__":
    test_integration()
