// Generated by Skyramp v1.3.19 on 2026-04-15 07:11:02.66466829 +0000 UTC m=+205.553039592
// Command: skyramp generate contract rest http://localhost:1337/api/foo \
// 		--framework playwright \
// 		--language typescript \
// 		--method PUT \
// 		--output foo_put_401_contract_test.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /api/foo PUT
test('testFooPut', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const fooPutRequestBody: string = `{}`;

    // Execute Request
    const fooPutResponse = await client.sendRequest({
        url: URL,
        path: "/api/foo",
        method: "PUT",
        body: fooPutRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(fooPutResponse.statusCode, 'status code').toBe(401);
});
