# Generated by Skyramp v1.3.16 on 2026-04-13 04:23:57.981254489 +0000 UTC m=+225.150589018
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output full_crud_test1_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_full-crud-test1.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    test1_POST_request_body = r'''{
        "data": {
            "slug": "test-article-full-crud",
            "title": "Test Article Full CRUD"
        }
    }'''

    # Execute Request
    test1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/test1",
        method="POST",
        body=test1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert test1_POST_response.status_code == 201
    assert skyramp.get_response_value(test1_POST_response, "data.id") is not None
    assert skyramp.get_response_value(test1_POST_response, "data.attributes.title") == "Test Article Full CRUD"
    assert skyramp.get_response_value(test1_POST_response, "data.attributes.slug") == "test-article-full-crud"

    # Execute Request
    test1_test1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/test1/{test1}",
        method="GET",
        headers=headers,
        path_params={"test1": skyramp.get_response_value(test1_POST_response, "data.id")}
    )
    # Generated Assertions
    assert test1_test1_GET_response.status_code == 200
    assert skyramp.get_response_value(test1_test1_GET_response, "data.id") == skyramp.get_response_value(test1_POST_response, "data.id")
    assert skyramp.get_response_value(test1_test1_GET_response, "data.attributes.title") == "Test Article Full CRUD"
    assert skyramp.get_response_value(test1_test1_GET_response, "data.attributes.slug") == "test-article-full-crud"

    # Request Body
    test1_test1_PUT_request_body = r'''{
        "data": {
            "slug": "test-article-full-crud",
            "title": "Updated Test Article"
        }
    }'''

    # Execute Request
    test1_test1_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/test1/{test1}",
        method="PUT",
        body=test1_test1_PUT_request_body,
        headers=headers,
        path_params={"test1": skyramp.get_response_value(test1_POST_response, "data.id")}
    )
    # Generated Assertions
    assert test1_test1_PUT_response.status_code == 200
    assert skyramp.get_response_value(test1_test1_PUT_response, "data.id") == skyramp.get_response_value(test1_POST_response, "data.id")
    assert skyramp.get_response_value(test1_test1_PUT_response, "data.attributes.title") == "Updated Test Article"
    assert skyramp.get_response_value(test1_test1_PUT_response, "data.attributes.slug") == "test-article-full-crud"

    # Execute Request
    test1_test1_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/test1/{test1}",
        method="DELETE",
        headers=headers,
        path_params={"test1": skyramp.get_response_value(test1_POST_response, "data.id")}
    )
    # Generated Assertions
    assert test1_test1_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
