// Generated by Skyramp v1.3.16 on 2026-04-13 00:27:01.723103874 +0000 UTC m=+311.612404569
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output media_library_ui_test.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/strapi-testb/strapi-testb/.skyramp/media_library_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

async function loginToStrapi(page, email, password) {
    const credentials: Record<string, any> = { email, password };
    // Wait for the login form to be ready before interacting
    await page.waitForSelector('input[name="email"]', { state: 'visible', timeout: 20000 });
    await page.getByRole("textbox", { name: "Email" }).fill(getValue(credentials, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(credentials, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise = page.waitForResponse("**/admin/login**");
    await page.getByRole("button", { name: "Login" }).click();
    await responsePromise;
}

test('testUi', async ({ page }) => {
    test.setTimeout(431000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Track page errors to detect rendering crashes (e.g. after login redirect)
    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto("http://localhost:1337/admin");

    await loginToStrapi(page, "admin@testbot.com", "TestBot123!");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:1337/admin/plugins/upload");
    await page.waitForLoadState('networkidle');
    await expect(page.getByRole("heading", { name: "Media Library" })).toContainText("Media Library");
    await expect(page.getByRole("button", { name: "Add new assets" })).toBeVisible();
});
