# Generated by Skyramp v1.3.16 on 2026-04-13 04:24:50.902244853 +0000 UTC m=+240.283667776
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output stream_from_urls_partial_failure_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_stream-from-urls-partial-failure.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    stream_from_urls_POST_request_body = r'''{
        "folderId": null,
        "urls": [
            "https://picsum.photos/id/237/200/300.jpg",
            "not-a-valid-url-xyz"
        ]
    }'''
    
    # Execute Request
    stream_from_urls_POST_response = client.send_request(
        url=URL_localhost,
        path="/upload/unstable/stream-from-urls",
        method="POST",
        body=stream_from_urls_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert stream_from_urls_POST_response.status_code == 200


if __name__ == "__main__":
    test_integration()
