# Generated by Skyramp v1.3.16 on 2026-04-13 04:26:58.156725507 +0000 UTC m=+343.988960093
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output strict_params_unknown_query_rejected_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_strict-params-unknown-query-rejected.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    articles_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="GET",
        headers=headers,
        query_params={"unknownParam": ["unexpected-value"]}
    )
    # Generated Assertions
    assert articles_GET_response.status_code == 400
    assert skyramp.get_response_value(articles_GET_response, "error") is not None
    assert skyramp.get_response_value(articles_GET_response, "error.status") == 400


if __name__ == "__main__":
    test_integration()
