# Generated by Skyramp v1.3.16 on 2026-04-13 04:26:55.890128169 +0000 UTC m=+341.722362775
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output strict_params_unknown_body_rejected_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_strict-params-unknown-body-rejected.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    articles_POST_request_body = r'''{
        "data": {
            "slug": "strict-params-test-article",
            "title": "Strict Params Test Article"
        },
        "unknownTopLevelKey": "unexpected-value"
    }'''
    
    # Execute Request
    articles_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/articles",
        method="POST",
        body=articles_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert articles_POST_response.status_code == 400
    assert skyramp.get_response_value(articles_POST_response, "error") is not None
    assert skyramp.get_response_value(articles_POST_response, "error.status") == 400


if __name__ == "__main__":
    test_integration()
