// Generated by Skyramp v1.3.16 on 2026-04-13 00:58:13.999286128 +0000 UTC m=+92.219588185
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output test2_unique_constraint_integration_test.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/scenario_test2-unique-constraint.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const test2PostRequestBody = `{
            "name": "test-unique-entry-skyramp",
            "type": "content"
        }`
    
    // Execute Request
    let test2PostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/test2",
        method:"POST",
        body:test2PostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(test2PostResponse.statusCode, 'status code').toBe(201);
    expect(getValue(test2PostResponse, "id"), 'id').not.toBeNull();
    expect(getValue(test2PostResponse, "name"), 'name').toBe("test-unique-entry-skyramp");
    expect(getValue(test2PostResponse, "type"), 'type').toBe("content");

    // Request Body
    const test2Post1RequestBody = `{
            "name": "test-unique-entry-skyramp",
            "type": "content"
        }`
    
    // Execute Request
    let test2Post1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/test2",
        method:"POST",
        body:test2Post1RequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(test2Post1Response.statusCode, 'status code').toBe(409);
});

