// Generated by Skyramp v1.3.19 on 2026-04-15 06:50:33.414924362 +0000 UTC m=+240.843495841
// Command: skyramp generate contract rest http://localhost:1337/bar \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output bar_patch_401_contract_test.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--request-data {"data":{"name":"test-update"}} \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /bar PATCH
test('testBarPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const barPatchRequestBody: string = `{
        "data": {
            "name": "test-update"
        }
    }`;

    // Execute Request
    const barPatchResponse = await client.sendRequest({
        url: URL,
        path: "/bar",
        method: "PATCH",
        body: barPatchRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(barPatchResponse.statusCode, 'status code').toBe(401);
});
