# Generated by Skyramp v1.3.19 on 2026-04-15 08:06:01.738211309 +0000 UTC m=+201.298770776
# Command: skyramp generate contract rest http://localhost:1337/api/foo \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

# contract test for /api/foo PUT
def test_foo_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    foo_PUT_response = client.send_request(
        url=URL,
        path="/api/foo",
        method="PUT",
        headers=headers
    )

    # Generated Assertions
    assert foo_PUT_response.status_code == 401


if __name__ == "__main__":
    test_foo_put()
