// Generated by Skyramp v1.3.19 on 2026-04-15 06:52:49.054970607 +0000 UTC m=+721.483756462
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output import_from_url_ui_test.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/strapi-testb/strapi-testb/.skyramp/import_from_url_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUi', async ({ page }) => {
    test.setTimeout(120000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Track page errors before any navigation
    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:1337/admin");
    await page.waitForLoadState('networkidle');

    const playwrightRequest1: Record<string, any> = {
        "email": "admin@testbot.com",
        "password": "TestBot123!"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest1, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest1, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/admin/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:1337/admin/plugins/upload");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Add new assets" }).click();
    await page.getByRole("tab", { name: "From url" }).click();
    await page.getByRole("textbox", { name: "URL(s)" }).fill("https://picsum.photos/id/237/200/300.jpg");
    await page.getByRole("button", { name: "Next" }).click();
    await expect(page.getByText("asset ready to upload")).toContainText("1 asset ready to upload");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/upload**");
    await page.getByRole("button", { name: "Upload 1 asset to the library" }).click();
    const response2 = await responsePromise2;

    // Assert the uploaded asset is visible in the library
    await expect(page.getByRole("heading", { name: "300.jpg" })).toBeVisible();

    // Assert no unexpected page errors occurred
    expect(errors.filter(e => !e.includes('ERR_CONNECTION_REFUSED') && !e.includes('Invalid hook call'))).toHaveLength(0);
});
