// Generated by Skyramp v1.3.19 on 2026-04-15 06:59:03.862642509 +0000 UTC m=+158.847417506
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output import_from_url_invalid_error_ui_test.spec.ts \
// 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/strapi-testb/strapi-testb/.skyramp/invalid_url_error_trace.zip

// Import of required libraries
import { test } from '@playwright/test';
import { expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testUiInvalidUrl', async ({ page }) => {
    test.setTimeout(110000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Track page errors before any navigation
    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));

    await page.goto("http://localhost:1337/admin");
    await page.waitForLoadState('networkidle');

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@testbot.com",
        "password": "TestBot123!"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/admin/login**");
    await page.getByRole("button", { name: "Login" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.goto("http://localhost:1337/admin/plugins/upload");
    await page.waitForLoadState('networkidle');
    await page.getByRole("button", { name: "Add new assets" }).click();
    await page.getByRole("tab", { name: "From url" }).click();
    await page.getByRole("textbox", { name: "URL(s)" }).fill("not-a-valid-url");
    await page.getByRole("button", { name: "Next" }).click();

    // Assert that the invalid URL error message is displayed
    await expect(page.getByText("One URL is invalid")).toBeVisible();

    // Assert no unexpected page errors occurred
    expect(errors.filter(e => !e.includes('ERR_CONNECTION_REFUSED') && !e.includes('Invalid hook call'))).toHaveLength(0);
});
