# Generated by Skyramp v1.3.19 on 2026-04-15 08:06:17.435713278 +0000 UTC m=+216.996272744
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output test2_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/strapi-testb/strapi-testb/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/strapi-testb/strapi-testb/tests/skyramp/scenario_test2-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:1337")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    test2_POST_request_body = r'''{
        "name": "unique-test-item"
    }'''
    
    # Execute Request
    test2_POST_response = client.send_request(
        url=URL_localhost,
        path="/test2",
        method="POST",
        body=test2_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert test2_POST_response.status_code == 201

    # Request Body
    test2_POST_1_request_body = r'''{
        "name": "unique-test-item"
    }'''
    
    # Execute Request
    test2_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/test2",
        method="POST",
        body=test2_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert test2_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
